### ISSUE TITLE
Won't install on ARM64 

### ISSUE THREAD

**Issue by oising** [pharring/FeatureFlags#19]
See: https://learn.microsoft.com/en-us/visualstudio/extensibility/arm64/target-arm64-visual-studio-extension?view=vs-2022

**Comment by oising** [comment]
Oh, there's a waiting PR for this: https://github.com/pharring/FeatureFlags/pull/18

@pharring ?

**Comment by pharring** [comment]
This will be fixed in release 1.0.10
